version: "3"

services:
  app:
    image: terrybrooks/doppler-test-rpt:latest
    build: .
    environment:
      - DISPLAY=0
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - DOPPLER_PROJECT=feature-report
      - DOPPLER_CONFIG=dev_personal
      - DOPPLER_ENV=dev
    privileged: true

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host